artifacts_root: artifacts

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ['train', 'test', 'validation']

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/dataset/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail
