import enum

class ImageValidation(str, enum.Enum):
    IMAGE_IS_VALID = 'IMAGE_IS_VALID'
    IMAGE_HAS_ALREADY_IN_DATABASE = 'IMAGE_HAS_ALREADY_IN_DATABASE'
    IMAGE_HAS_NO_FACE = 'IMAGE_HAS_NO_FACE'
    NOT_HUMAN_FACE = 'NOT_HUMAN_FACE'
    INPUT_IS_NOT_IMAGE_FILE = 'INPUT_IS_NOT_IMAGE_FILE'