  name: "infer_text_rec"
  platform: "onnxruntime_onnx"
  max_batch_size: 8
  input [
    {
      name: "x"
      data_type: TYPE_FP32
      dims: [3,48,-1]
    }
  ]
output [
    {
      name: "softmax_2.tmp_0"
      data_type: TYPE_FP32
      dims: [-1,97]
    }
  ]

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
  ]